language: python
dist: bionic  # ubuntu-18.04
python:
    - '3.6'
install:
    - sudo apt-get -y install neovim
    - pip install codecov
    - pip install covimerage
script:
    - python setup.py coverage --xml
    - codecov --token=836e8801-c039-4f16-8b36-717f92ff7664
