filetype off

" plugin settings
set rtp+=.test_deps/vader.vim
set rtp+=.test_deps/jellybeans.vim
set rtp+=.

" vader settings
filetype plugin indent on
syntax enable

" personal settings
colorscheme jellybeans
map <leader>q :q<CR>
